### ISSUE TITLE
requirements.txt doesn't work

### ISSUE THREAD

**Issue by valsworthen** [kevinduh/san_mrc#14]
`pip install -r requirements.txt` cannot download pytorch

Collecting pytorch==0.4.0 (from -r requirements.txt (line 3))
  Could not find a version that satisfies the requirement pytorch==0.4.0 (from -r requirements.txt (line 3)) (from versions: 0.1.2)
No matching distribution found for pytorch==0.4.0 (from -r requirements.txt (line 3))

**Comment by saket-maheshwary** [comment]
@valsworthen 

I also faced the same issue but then i removed the line mentioning pytorch in requirements.txt and then installed pytorch independently.

You can install the pytorch preference based on your system configration from https://pytorch.org/

**Comment by namisan** [comment]
I've updated the requirement file and published my docker as well.
