### ISSUE TITLE
whaich parameters should be considered for machine comprehension performance test ?

### ISSUE THREAD

**Issue by munaAchyuta** [kevinduh/san_mrc#6]

**Comment by munaAchyuta** [comment]
even when i tried with some training dataset, there also model is failing to give good results and the result for same question is varying with every new prediction.  like below example from training data.

context with actual answer : 
`{"context": "Architecturally, the school has a Catholic character. Atop the Main Building's gold dome is a golden statue of the Virgin Mary. Immediately in front of the Main Building and facing it, is a copper statue of Christ with arms upraised with the legend \"Venite Ad Me Omnes\". Next to the Main Building is the Basilica of the Sacred Heart. Immediately behind the basilica is the Grotto, a Marian place of prayer and reflection. It is a replica of the grotto at Lourdes, France where the Virgin Mary reputedly appeared to Saint Bernadette Soubirous in 1858. At the end of the main drive (and in a direct line that connects through 3 statues and the Gold Dome), is a simple, modern stone statue of Mary.", "qas": [{"answers": [{"answer_start": 515, "text": "Saint Bernadette Soubirous"}], "question": "To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?", "id": "5733be284776f41900661182"}, {"answers": [{"answer_start": 188, "text": "a copper statue of Christ"}], "question": "What is in front of the Notre Dame Main Building?", "id": "5733be284776f4190066117f"}, {"answers": [{"answer_start": 279, "text": "the Main Building"}], "question": "The Basilica of the Sacred heart at Notre Dame is beside to which structure?", "id": "5733be284776f41900661180"}, {"answers": [{"answer_start": 381, "text": "a Marian place of prayer and reflection"}], "question": "What is the Grotto at Notre Dame?", "id": "5733be284776f41900661181"}, {"answers": [{"answer_start": 92, "text": "a golden statue of the Virgin Mary"}], "question": "What sits on top of the Main Building at Notre Dame?", "id": "5733be284776f4190066117e"}]}`

model response : 
'question': 'To whom did the Virgin Mary allegedly appear in 1858 in Lourdes France?'
'pred-answer': "Architecturally, the school has a Catholic character. Atop the Main Building's gold dome is a golden statue of"

'question': 'What is in front of the Notre Dame Main Building?'
'pred-answer': 'main drive (and in a direct'

'question': 'The Basilica of the Sacred heart at Notre Dame is beside to which structure?'
'pred-answer': 'direct line that connects'

'question': 'What is the Grotto at Notre Dame?'
'pred-answer': 'that connects through'

'question': 'What sits on top of the Main Building at Notre Dame?'
'pred-answer': 'with arms upraised with the legend "Venite Ad Me Omnes". Next'

Thanks.

**Comment by namisan** [comment]
Could you check the eval script in the train.py, where you can find an eval function?
I'm on vocation in the coming weeks, and will work on the prediction pipeline later. Thanks,

**Comment by munaAchyuta** [comment]
Hi @namisan 

eval gave : {"exact_match": 75.96972563859981, "f1": 84.00045291639158}

Thanks.
