### ISSUE TITLE
About the default model settings

### ISSUE THREAD

**Issue by jihunchoi** [kevinduh/san_mrc#8]
Hi, thank you for releasing the code.
As far as I understood, the default configuration sets `decoder_mem_type` to 0, and thus it does not use the stochastic answer network architecture and `decoder_mem_drop_p` is ignored.
The default setting yields a fairly good performance of EM 76.3 and F1 84.1, but can you share the arguments used in experiments for further exploration?
Thanks!

**Comment by namisan** [comment]
I optimized the model arch recently, the baseline model can obtain a good performance. If you set decoder_mem_type=1 and decoder_mem_drop_p=0.2, it should obtain 76.8/84.6 (EM/F1).
